Public Class InternalSoftwareStartup
    Shared Sub Startup()
        ' 登錄版本載入程式
        ServerVersionListLoader.RegisterVersionListFunction(Of VanillaServer)(AddressOf VanillaServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of CraftBukkitServer)(AddressOf CraftBukkitServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of SpigotServer)(AddressOf SpigotServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of SpigotWithGitServer)(AddressOf SpigotWithGitServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of PaperServer)(AddressOf PaperServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of AkarinServer)(AddressOf AkarinServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of ForgeServer)(AddressOf ForgeServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of SpongeVanillaServer)(AddressOf SpongeVanillaServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of CauldronServer)(AddressOf ContigoServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of ThermosServer)(AddressOf ThermosServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of ContigoServer)(AddressOf ContigoServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of KettleServer)(AddressOf KettleServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of BDSServer)(AddressOf BDSServer.GetVersionList)
        ServerVersionListLoader.RegisterVersionListFunction(Of NukkitServer)(AddressOf NukkitServer.GetVersionList)
        ' 登錄伺服器軟體
        ServerMaker.RegisterServerSoftware(Of VanillaServer)("Vanilla", "原版 (Java)")
        ServerMaker.RegisterServerSoftware(Of CraftBukkitServer)("CraftBukkit", "CraftBukkit")
        ServerMaker.RegisterServerSoftware(Of SpigotServer)("Spigot", "Spigot")
        ServerMaker.RegisterServerSoftware(Of SpigotWithGitServer)("Spigot_Git", "Spigot")
        ServerMaker.RegisterServerSoftware(Of PaperServer)("Paper", "Paper")
        ServerMaker.RegisterServerSoftware(Of AkarinServer)("Akarin", "Akarin")
        ServerMaker.RegisterServerSoftware(Of ForgeServer)("Forge", "Forge")
        ServerMaker.RegisterServerSoftware(Of SpongeVanillaServer)("SpongeVanilla", "SpongeVanilla")
        ServerMaker.RegisterServerSoftware(Of CauldronServer)("Cauldron", "Cauldron")
        ServerMaker.RegisterServerSoftware(Of ThermosServer)("Thermos", "Thermos")
        ServerMaker.RegisterServerSoftware(Of ContigoServer)("Contigo", "Contigo")
        ServerMaker.RegisterServerSoftware(Of KettleServer)("Kettle", "Kettle")
        ServerMaker.RegisterServerSoftware(Of BDSServer)("VanillaBedrock", "BDS")
        ServerMaker.RegisterServerSoftware(Of NukkitServer)("Nukkit", "NukkitX")
    End Sub
End Class
